# Generated by Django 3.1.5 on 2021-02-05 14:37

from django.db import migrations

def createFirstThread(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Thread = apps.get_model('backend', 'Thread')
    db_alias = schema_editor.connection.alias
    Thread.objects.using(db_alias).bulk_create([
        Thread(name="All")
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(createFirstThread), 
    ]
